### ISSUE TITLE
[bug] Mediakit::FFmpeg#run can't accept nice options

### ISSUE THREAD

**Issue by ainame** [ainame/mediakit#4]
```
[ainame@ainame-dev server]$ bundle exec ruby sample.rb
/usr/local/lib/ruby/2.2.0/shellwords.rb:73:in `shellsplit': undefined method `scan' for 10:Fixnum (NoMethodError
)
        from /opt/data/workspace/server/vendor/bundle/ruby/2.2.0/gems/mediakit-0.0.11/lib/mediakit/utils/shell_e
scape.rb:19:in `escape_with_split'
        from /opt/data/workspace/server/vendor/bundle/ruby/2.2.0/gems/mediakit-0.0.11/lib/mediakit/utils/shell_e
scape.rb:9:in `escape'
        from /opt/data/workspace/server/vendor/bundle/ruby/2.2.0/gems/mediakit-0.0.11/lib/mediakit/utils/process
_runner.rb:80:in `build_command'
        from /opt/data/workspace/server/vendor/bundle/ruby/2.2.0/gems/mediakit-0.0.11/lib/mediakit/drivers.rb:56
:in `command'
        from /opt/data/workspace/server/vendor/bundle/ruby/2.2.0/gems/mediakit-0.0.11/lib/mediakit/ffmpeg.rb:25:
in `command'
        from sample.rb:27:in `<main>'
```

**Comment by ainame** [comment]
fixed 7d4e3074135b514b264f916836873acbba6bb5cf
and released!
